openapi: 3.0.0
info:
  title: ActionEarn
  version: 1.0.0
servers:
  - url: http://localhost:3000
security:
  - bearerAuth: []
paths:
  /api/action/earn/create:
    $ref: paths/api_action_earn_create.yaml
  /api/action/earn/update:
    $ref: paths/api_action_earn_update.yaml
  /api/action/earn/get:
    $ref: paths/api_action_earn_get.yaml
  /api/action/earn/all:
    $ref: paths/api_action_earn_all.yaml
  /api/action/earn/delete:
    $ref: paths/api_action_earn_delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
